### ISSUE TITLE
Module 'JKVValue' not found

### ISSUE THREAD

**Issue by GouthamKumar** [rabbitmq/rabbitmq-objc-client#115]
Hello,
  I am trying to get updated from publisher. Installed pods like u suggested in doc. But I am getting JKVValue module not found in RMQValue.h class. Please help me.

![screen shot 2017-03-01 at 7 29 22 am](https://cloud.githubusercontent.com/assets/1508464/23442855/3b9a453e-fe51-11e6-8516-09b1d774427c.png)
Thanks in advance.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
This library manages its dependencies [via Carthage](https://github.com/Carthage/Carthage#getting-started).

**Comment by sebasborda** [comment]
Hi Guys, I'm having the same issue try to use the lib on OSX, the problem is that xcode is not recognizing the @import ... but if I replace it with #import <... everything starts to work, can you please do that little change?. The same problem is happening with "@import CocoaAsyncSocket;" and "@import JKVValue;"

**Comment by michaelklishin** [comment]
We won't be making any changes without more information.

What XCode version is used? What iOS or macOS release is targeted? Has Carthage been used to provision and build dependencies?

**Comment by sebasborda** [comment]
I'm using CocoaPods as it is explained on the readme, and all the dependencies were installed.
XCode: 10.2.1
macOS Target: 10.14

**Comment by michaelklishin** [comment]
It's hard to suggest much without having an example project but there are [project settings that might potentially be highly relevant here](https://stackoverflow.com/questions/27640420/using-import-in-a-cocoapods-project).

Consider putting together an example project that we can use to reproduce and publishing it to GitHub or a similar public Git repository hosting.

**Comment by sebasborda** [comment]
I made a new project, it has no code, configuration or other libraries more than RMQClient and I have the very same problem.

you can se it here
https://github.com/sebasborda/RMQClientOSX

**Comment by michaelklishin** [comment]
Thanks. I can reproduce and have evidence of module imports vs. a plain old import being very much dependent on project build settings (which CocoaPods dictates, for example). Apparently when frameworks are not used (which is the case in the project above), [module imports](https://clang.llvm.org/docs/Modules.html#introduction) are recommend against by [one of our dependencies](https://github.com/robbiehanson/CocoaAsyncSocket#importing). I'm not familiar enough with Clang module implementation to provide an explanation but switching to plain old imports works for every case I've, including the project above.

**Comment by michaelklishin** [comment]
@sebasborda can you please give `master` a try?

**Comment by sebasborda** [comment]
It is working with the last changes from master, Thanks!!
