### ISSUE TITLE
Module JKVValue not found

### ISSUE THREAD

**Issue by dhson04** [rabbitmq/rabbitmq-objc-client#116]
I create new project and use pod command: `pod 'RMQClient', '~> 0.10.0'`
then choose **xcworkspace** to open then build but show alert error RMQClient lib `Module 'JKVValue' not found` 
Please show me to resolve this issuse. Thanks

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Same question as #115.

**Comment by dhson04** [comment]
Thank you! I'm sorry for not checking before post issuse.
