### ISSUE TITLE
Code=406 "PRECONDITION_FAILED - cannot redeclare exchange 'xxxx_exchang' in vhost 'xxxx' with different type, durable, internal or autodelete value"

### ISSUE THREAD

**Issue by AlbertCamusSZB** [rabbitmq/rabbitmq-objc-client#119]
Error Domain=com.rabbitmq.rabbitmq-objc-client Code=406 "PRECONDITION_FAILED - cannot redeclare exchange 'xxxx_exchang' in vhost 'xxxx' with different type, durable, internal or autodelete value" UserInfo={NSLocalizedDescription=PRECONDITION_FAILED - cannot redeclare exchange 'xxxx_exchang' in vhost 'xxxx' with different type, durable, internal or autodelete value}

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with.

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Please help others help you by providing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server and client versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thanks you.

**Comment by michaelklishin** [comment]
The message says it all: you cannot re-declare exchanges or queues with different properties. Either change the properties to match or delete the exchange and try again.

**Comment by AlbertCamusSZB** [comment]
Thank you very much for your advice, my problem has been solved, you are really good！
