### ISSUE TITLE
dyld: Library not loaded: @rpath/RMQClient.framework/Versions/A/RMQClient

### ISSUE THREAD

**Issue by pixelskull** [rabbitmq/rabbitmq-objc-client#122]
Hey there, 

I'm trying to use RMQClient under macOS, unfortunately the following error occurs: 

```
dyld: Library not loaded: @rpath/RMQClient.framework/Versions/A/RMQClient
  Referenced from: /Users/pascal/Library/Developer/Xcode/DerivedData/ComputeUnitHandler-hbibhobjmehbsgdqlqusmvzajeex/Build/Products/Debug/ComputeUnitHandler
  Reason: image not found 
```

Installation was via Carthage, and I'm using xcode-beta (xcode 9). 

Framework was linked via "Link Binary with Libraries" also the "RMQClient.framework" is added to "Copy files section". 

Is there some fix for this behaviour?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
I don't have an XCode 9 machine to try on but almost certainly this is a generic XCode and Carthage setup question such as [1][2] that has nothing to do specifically with this library.

1. https://github.com/Alamofire/Alamofire/issues/101
2. https://github.com/Carthage/Carthage/issues/616

**Comment by michaelklishin** [comment]
I'd open [RabbitMQ tutorials](https://github.com/rabbitmq/rabbitmq-tutorials/) in Objective-C or Swift, try them out in XCode 9 and compare to your project. They are known to work with the GA version of XCode.

**Comment by pixelskull** [comment]
@michaelklishin Thanks for quick reply, sorry for spamming here. 

Are these tutorials working under macOS, because in the Cartfile version `"v0.10.0"` is set. I have found that this version don't build for mac, only version `"v0.11.0"` does.

**Comment by michaelklishin** [comment]
There is no [0.11.0 release of this library](https://github.com/rabbitmq/rabbitmq-objc-client/tags). Are you referring ot OS X 10.10? I'm quite sure we have targeted 10.11 for a long time now, and [.travis.yml confirms this](https://github.com/rabbitmq/rabbitmq-objc-client/blob/master/.travis.yml).

**Comment by pixelskull** [comment]
No, just put this version in Cartfile. I'm currently using macOS 10.12. 

Found `0.11.0` as milestone here in this [issue](https://github.com/rabbitmq/rabbitmq-objc-client/issues/55#event-832774032)... 

With the version tag `0.11.0` the Mac target was build, with `0.10.0` not. 


Also tried the Cocoapod installation which is dumping this: 

```
Analyzing dependencies
[!] The platform of the target `ComputeUnitHandler` (macOS 10.12) is not compatible with `RMQClient (0.10.0)`, which does not support `osx`.

[!] Automatically assigning platform osx with version 10.12 on target ComputeUnitHandler because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

Is all of this happening because my Mac is running 10.12?

**Comment by pixelskull** [comment]
Oh and here is the Carthage output for bootstrapping via  `carthage bootstrap --platform osx`

```
*** No Cartfile.resolved found, updating dependencies
*** Fetching rabbitmq-objc-client
*** Fetching CocoaAsyncSocket
*** Fetching JKVValue
*** Checking out CocoaAsyncSocket at "7.6.1"
*** Checking out JKVValue at "v1.3.3"
*** Checking out rabbitmq-objc-client at "v0.10.0"
*** xcodebuild output can be found in /var/folders/h8/hjz_plfj4p5gls5v9ww7tcg40000gn/T/carthage-xcodebuild.WaLUb8.log
*** Building scheme "Mac Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "JKVValue-OSX" in JKVValue.xcodeproj
*** Skipped building rabbitmq-objc-client due to the error:
Dependency "rabbitmq-objc-client" has no shared framework schemes for any of the platforms: Mac

If you believe this to be an error, please file an issue with the maintainers at https://github.com/rabbitmq/rabbitmq-objc-client/issues/new

```

**Comment by pixelskull** [comment]
> I don't have an XCode 9 machine to try on but almost certainly this is a generic XCode and Carthage setup question such as [1][2] that has nothing to do specifically with this library.
> 
> Alamofire/Alamofire#101
> Carthage/Carthage#616

So, finished every possible Solution from there, nothing has worked. 

@michaelklishin do you have any suggestion? I don't think that the problem with carthage/cocoapods and macOS is a good topic for Google Groups etc. 

Since I'm not into building packages.... Is it possible that the package definitions have some errors that could produce my problem?

**Comment by Gunjan-Makwana** [comment]
I am having same issue for installing a technical software on my new MacBook Air M1. Can anyone help me with this?

dyld: Library not loaded: @rpath/QGpCoreTools.framework/Versions/2/QGpCoreTools
  Referenced from: /Applications/Geopsy.org/3.3/Utilities/geopsy
  Reason: image not found
