### ISSUE TITLE
Unable to receive messages

### ISSUE THREAD

**Issue by yarodevuci** [rabbitmq/rabbitmq-objc-client#139]
I am using ubuntu, When I run flask server on EC2 directly I have no problem to connect to rabbitMq from iOS device, but when I move server to apache2 and use mod wsgi I am unable to connect to it.
I wrote python scrip and it also can receive messages.
However on iOS device I am not able too.

Anyone know what could be the issue?
RabbitMQ v: 3.6.15 Erlang 18.3

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
