### ISSUE TITLE
Not able to provide custom connection name

### ISSUE THREAD

**Issue by grsteffens** [rabbitmq/rabbitmq-objc-client#154]
Contrary to the Java SDK, it appears that there is not a way to provide a custom `connection_name` for a `RMQConnection`. Does this version of the client support a way to name the connection?

**Comment by michaelklishin** [comment]
User-provided connection name is nothing more than a [`connection_name` string value in the `client_properties` table](https://github.com/rabbitmq/rabbitmq-java-client/blob/6a6b26c309aa77f6050eeeef088f75ddefe9a9e3/src/main/java/com/rabbitmq/client/impl/AMQConnection.java#L514).

This client [hardcodes the table](https://github.com/rabbitmq/rabbitmq-objc-client/blob/fef676e4c0ddcf66510987265e781914f83f339b/RMQClient/RMQHandshaker.m#L113). I will file a specific issue since this is a question.

**Comment by grsteffens** [comment]
@michaelklishin thank you for the quick response. I can submit a PR for the change if you would like. If so, just assign me the issue.
