### ISSUE TITLE
Provide a way to set a user-provided connection name

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-objc-client#155]
Started as a question in #154.

This client currently [hardcodes `client_properties`](https://github.com/rabbitmq/rabbitmq-objc-client/blob/fef676e4c0ddcf66510987265e781914f83f339b/RMQClient/RMQHandshaker.m#L113) and so there is no way to provide a user-specific connection name or any other property. Ideally there should be a connection factory field for the name and a dictionary that would be merged with a set of predefined fields in addition to that.

**Comment by michaelklishin** [comment]
@grsteffens I'm afraid I cannot assign this issue to someone who isn't a collaborator on this repo. While I can add you it may be overkill for a single change. In any case, I am happy to get it very soon. You can help by giving the new API elements a shot :)

**Comment by grsteffens** [comment]
@michaelklishin understood. I really just needed this as soon as possible due to an implementation I am working on and wanted to offer my assistance as to help expedite the enhancement. Just so I have an idea, what would the timeline look like for another established collaborator to complete this task?

p.s - Regarding the new API elements, where can those be found? 

Thanks!

**Comment by michaelklishin** [comment]
@grsteffens in a pull request I am yet to submit. It should be done by tomorrow.

Now that you can run the tests in the `RMQClient` scheme against any RabbitMQ node (no need to preconfigure), it should take less than an hour. If you can't wait until tomorrow, feel free to look into it.
Otherwise I'm happy to do it.

**Comment by grsteffens** [comment]
@michaelklishin that is awesome. I appreciate the quick turnaround on this. Let me know if there is anything I can do to assist.
