### ISSUE TITLE
Linux swift support

### ISSUE THREAD

**Issue by sergeydi** [rabbitmq/rabbitmq-objc-client#165]
Hi,
How to build library for use in linux swift?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This was previously discussed in #14 and #87.

This client is implemented in Objective-C and that won't change. A pure Swift might be an option but likely will have to use a different set of I/O dependencies. I don't know when our team would have the cycles to work on that. This is open source software, though, so you are welcome to contribute a prototype.
