### ISSUE TITLE
Sending basic properties in basic publish

### ISSUE THREAD

**Issue by sasikiran** [rabbitmq/rabbitmq-objc-client#65]
In C#'s EasyNetQ RabbitMQ library, you can create MessageProperties object and configure custom userId, replyTo etc. and pass the properties in `this.Bus.Publish()` method.

Similarly, in Java's example shown in RPCClient.java, you see:
`channel.basicPublish("", requestQueueName, props, message.getBytes("UTF-8"))` where props are the custom basic properties.

Lastly, in C library port, `amqp_basic_publish()` accepts the same custom properties in &properties. 

How do I pass in the same basic properties in this library? I checked `basicPublish` method declared in `RMQChannel`, and it looks like the method doesn't seem to support properties parameter. 

I also tried creating `RMQBasicPublish` object and then created `RMQContentHeader` with properties such as `RMQBasicContentType`, `RMQBasicUserId`, `RMQBasicReplyTo` etc. 

However, I am stuck here not knowing what to do with the content header and how do I do a basic publish with the data I have. Any pointers here?

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users or Stack Overflow. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
@sasikiran see https://github.com/rabbitmq/rabbitmq-objc-client/pull/64. In other words, without that PR there is no way to specify message properties. That's an oversight in the library that will be addressed in the future.

**Comment by camelpunch** [comment]
Opening as a feature request in favour of #64

**Comment by camelpunch** [comment]
@sasikiran @hasbean with those three commits you can specify properties on a channel with basicPublish in a very manual way, by setting RMQBasic* types in an array, similar to PR #64 . I haven't yet implemented all of the encoding for every field type, though (including e.g. nested tables and nils), so you may run into issues when sending. I also haven't even looked at receiving properties through consumers.

The plan is to have RMQQueue and RMQExchange be the main interfaces for setting properties. They'll be settable through parameters with regular Objective-C / Swift types.

I'll be working on this until it's done, so tomorrow or Thursday **might** see this finished. Otherwise some time next week.

**Comment by sasikiran** [comment]
Thank you @camelpunch and @hasbean. I just checked out the API. This is so cool!
